spring.application.name=defense-scheduler

# --- SUPABASE CONNECTION (Using environment variables) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- OTHER CONFIGURATIONS ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# --- TIMEFOLD SOLVER CONFIGURATION ---
timefold.solver.termination.spent-limit=10s
timefold.solver.daemon=false

logging.level.ai.timefold.solver=INFO
# Or use DEBUG to see step-by-step details
# logging.level.ai.timefold.solver=DEBUG

# --- JWT CONFIGURATION ---
jwt.secret=${JWT_SECRET:YourSuperSecretKeyForJWTTokenGenerationMinimum256BitsLong!}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Resend API
resend.api.key=${RESEND_API_KEY}
resend.from.email=noreply@labmanagement.online
