spring.application.name=defense-scheduler

# --- K?T N?I SUPABASE (Dùng bi?n môi tr??ng) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- C?U HÌNH KHÁC ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false