spring.application.name=defense-scheduler

# --- KET NOI DATABASE ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CAU HINH KHAC ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# --- TIMEFOLD SOLVER CONFIGURATION ---
timefold.solver.termination.spent-limit=10s
timefold.solver.daemon=false

logging.level.ai.timefold.solver=INFO

